# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/huawei/hi6250-9-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter agassi2 anne bach2 bond figo florida leland,$(TARGET_DEVICE)),)

endif
